name: Die Command
version: '1.0'
main: me.notmithun.diecommand.DieCommand
api-version: '1.19'

commands:
  die:
    description: A die command. Used to kill yourself and cannot be used to kill others.
    usage: "/<command>"